# Generated by Django 5.1.5 on 2025-01-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_remove_trainer_user_trainer_email_trainer_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='current_trainees',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
