# Generated by Django 5.1.5 on 2025-01-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('trainee', 'Trainee'), ('trainer', 'Trainer'), ('admin', 'Admin'), ('pending_trainer', 'Pending Trainer'), ('pending_admin', 'Pending Admin')], default='trainee', max_length=20, null=True),
        ),
    ]
